const data = {
  products: [
    {
      name: 'Starter',
      slug: 'starter-package',
      category: 'Short-Term',
      image: '/images/starter01.jpg',
      price: 5000,
      countInStock: 1000000,
      brand: 'Starters',
      rating: 4,
      numReviews: 15,
      description: '30% Interest',
    },
    {
      name: 'Silver',
      slug: 'silver-package',
      category: 'Short-Term',
      image: '/images/silver01.png',
      price: 10000,
      countInStock: 1000000,
      brand: 'Silver',
      rating: 4.5,
      numReviews: 15,
      description: '30% Interest',
    },
    {
      name: 'Gold',
      slug: 'gold-package',
      category: 'Medium-Term',
      image: '/images/gold01.jpg',
      price: 20000,
      countInStock: 1000000,
      brand: 'Gold',
      rating: 5,
      numReviews: 20,
      description: '40% Interest',
    },
    {
      name: 'Diamond',
      slug: 'diamond-package',
      category: 'Medium-Term',
      image: '/images/diamond01.jpg',
      price: 50000,
      countInStock: 1000000,
      brand: 'Diamond',
      rating: 5,
      numReviews: 20,
      description: '40% Interest',
    },
    {
      name: 'Platinium',
      slug: 'platinium-package',
      category: 'Medium-Term',
      image: '/images/platinium01.png',
      price: 100000,
      countInStock: 1000000,
      brand: 'Platinium',
      rating: 5,
      numReviews: 30,
      description: '45% Interest',
    },
    {
      name: 'Master',
      slug: 'master-package',
      category: 'Medium-Term',
      image: '/images/master03.png',
      price: 200000,
      countInStock: 1000000,
      brand: 'Master',
      rating: 5,
      numReviews: 30,
      description: '45% Interest',
    },
    {
      name: 'Grandmaster',
      slug: 'gmaster-package',
      category: 'Long-Term',
      image: '/images/gmaster01.png',
      price: 500000,
      countInStock: 1000000,
      brand: 'Grandmaster',
      rating: 5,
      numReviews: 30,
      description: '50% Interest',
    },
    {
      name: 'Legendary',
      slug: 'legend-package',
      category: 'Long-Term',
      image: '/images/legendary04.jpg',
      price: 1000000,
      countInStock: 1000000,
      brand: 'Legendary',
      rating: 5,
      numReviews: 30,
      description: '50% Interest',
    },
  ],
}

export default data

// const data = {
//   products: [
//     {
//       name: 'Nike XL Shirt',
//       slug: 'nike-xl-shirt',
//       category: 'Shirt',
//       image: '/images/shirt1.svg',
//       price: 120,
//       countInStock: 10,
//       brand: 'Nike',
//       rating: 5,
//       numReviews: 10,
//       description: 'High Quality Shirt',
//     },
//     {
//       name: 'Nike Slim Shirt',
//       slug: 'nike-slim-shirt',
//       category: 'Shirt',
//       image: '/images/shirt2.svg',
//       price: 100,
//       countInStock: 10,
//       brand: 'Nike',
//       rating: 4.5,
//       numReviews: 12,
//       description: 'High Quality Shirt',
//     },

//     {
//       name: 'Nike Large Shirt',
//       slug: 'nike-lg-shirt',
//       category: 'Shirt',
//       image: '/images/shirt2.svg',
//       price: 60,
//       countInStock: 10,
//       brand: 'Nike',
//       rating: 4,
//       numReviews: 15,
//       description: 'High Quality Shirt',
//     },

//     {
//       name: 'Nike XL Shirt',
//       slug: 'nike-xl1-shirt',
//       category: 'Shirt',
//       image: '/images/shirt1.svg',
//       price: 120,
//       countInStock: 10,
//       brand: 'Nike',
//       rating: 3.5,
//       numReviews: 8,
//       description: 'High Quality Shirt',
//     },

//     {
//       name: 'Nike XL Pant',
//       slug: 'nike-xl-pant',
//       category: 'Pant',
//       image: '/images/pant1.svg',
//       price: 90,
//       countInStock: 10,
//       brand: 'Nike',
//       rating: 3,
//       numReviews: 14,
//       description: 'High Quality Shirt',
//     },

//     {
//       name: 'Nike L Pant',
//       slug: 'nike-l-pant',
//       category: 'Pant',
//       image: '/images/pant2.svg',
//       price: 80,
//       countInStock: 10,
//       brand: 'Nike',
//       rating: 4.5,
//       numReviews: 5,
//       description: 'High Quality Pant',
//     },

//     {
//       name: 'Nike SM Pant',
//       slug: 'nike-sm-pant',
//       category: 'Pant',
//       image: '/images/pant3.svg',
//       price: 70,
//       countInStock: 10,
//       brand: 'Nike',
//       rating: 4,
//       numReviews: 3,
//       description: 'High Quality Pant',
//     },
//     {
//       name: 'Nike L Pant',
//       slug: 'nike-ll-pant',
//       category: 'Pant',
//       image: '/images/pant2.svg',
//       price: 80,
//       countInStock: 10,
//       brand: 'Nike',
//       rating: 3,
//       numReviews: 4,
//       description: 'High Quality Pant',
//     },
//   ],
// }

// export default data
